/** Block.json attribute definitions for responsive spacing (Advanced tab). */
export const advancedAttributes = {
	cbPaddingTop: { type: 'string', default: '' },
	cbPaddingRight: { type: 'string', default: '' },
	cbPaddingBottom: { type: 'string', default: '' },
	cbPaddingLeft: { type: 'string', default: '' },
	cbPaddingTopTablet: { type: 'string', default: '' },
	cbPaddingTopMobile: { type: 'string', default: '' },
	cbPaddingRightTablet: { type: 'string', default: '' },
	cbPaddingRightMobile: { type: 'string', default: '' },
	cbPaddingBottomTablet: { type: 'string', default: '' },
	cbPaddingBottomMobile: { type: 'string', default: '' },
	cbPaddingLeftTablet: { type: 'string', default: '' },
	cbPaddingLeftMobile: { type: 'string', default: '' },
	cbPaddingUnit: { type: 'string', default: 'px' },
	cbPaddingLinked: { type: 'boolean', default: false },
	cbMarginTop: { type: 'string', default: '' },
	cbMarginRight: { type: 'string', default: '' },
	cbMarginBottom: { type: 'string', default: '' },
	cbMarginLeft: { type: 'string', default: '' },
	cbMarginTopTablet: { type: 'string', default: '' },
	cbMarginTopMobile: { type: 'string', default: '' },
	cbMarginRightTablet: { type: 'string', default: '' },
	cbMarginRightMobile: { type: 'string', default: '' },
	cbMarginBottomTablet: { type: 'string', default: '' },
	cbMarginBottomMobile: { type: 'string', default: '' },
	cbMarginLeftTablet: { type: 'string', default: '' },
	cbMarginLeftMobile: { type: 'string', default: '' },
	cbMarginUnit: { type: 'string', default: 'px' },
	cbMarginLinked: { type: 'boolean', default: false },
	cbAdvancedBackgroundColor: { type: 'string', default: '' },
};
